let suggestions = [
"anime",
"anime download",
"anime watch online",
"anime pictures",
"animation in css",
"bbc",
"birthday wishes",
"bbc latest news",
"cartoon",
"cartoon network",
"coronavirus",
"coronavirus updates",
"coronavirus in pakistan",
"dollar to pkr",
"dollar to euro",
"download",
"download google play store",
"download google play",
"download google chrome",
"earthquake",
"earthquake today",
"earthquake in pakistan",
"facebook",
"facebook login",
"facebook icon",
"google",
"google font",
"google classroom",
"google drive",
"google photos",
"how to use box shadow in css",
"how to learn css",
"how to use button in html",
"how to learn graphic designing online",
"how to link css to html",
"iphone",
"iphone 12",
"iphone se",
"iphone 12 price in pakistan",
"iphone 12 specs",
"jobs near me",
"jobs lahore",
"js",
"js tutorial",
"karachi",
"karachi weather",
"lahore",
"lahore weather",
"messenger",
"messenger download",
"naruto",
"naruto download",
"online class",
"online word",
"online games",
"pakistan",
"pakistan sports",
"qoutes",
"quotes about life",
"quotes of the day",
"redmi note 8",
"redmi note 8 pro",
"redmi note 9",
"save water poster",
"save the earth",
"translate english to urdu",
"translate english to arabic",
"usa today",
"usa map",
"whats the capital of pakistan",
"whats the capital of india",
"youtube music",
"youtube",
"youtube to mp3",
"zong",
"zong helpline",
"zoo",
"zoo lahore",
];
